export const masterStudios = [
  {
    id: 1,
    url: "https://isleofany.com",
    title: "Isle of Any",
    tags: ["Creative Studio"],
  },
  {
    id: 2,
    url: "https://kuhlandhan.com/",
    title: "Kuhl & Han",
    tags: ["Motion", "CGI"],
  },
  { id: 3, url: "https://cylndr.com/", title: "CYLNDR", tags: ["Production"] },
  {
    id: 4,
    url: "https://www.cartelandco.com/",
    title: "Cartel & Co",
    tags: ["Agency"],
  },
  {
    id: 5,
    url: "https://hark.com/",
    title: "Hark",
    tags: ["Strategy", "Design"],
  },
  {
    id: 6,
    url: "https://cotton.design/",
    title: "Cotton Design",
    tags: ["Digital", "Tech"],
  },
  {
    id: 7,
    url: "https://www.instagram.com/ales_santos/",
    title: "Ale Santos",
    tags: ["Art Direction"],
  },
  {
    id: 8,
    url: "https://the-brandidentity.com/project/defying-norms-at-21-how-cotton-design-weaves-technology-and-art-into-backslashs-visual-language",
    title: "The Brand Identity (Cotton)",
    tags: ["Editorial"],
  },
  {
    id: 9,
    url: "http://resourcela.com",
    title: "Resource LA",
    tags: ["Production"],
  },
  {
    id: 10,
    url: "https://pioneer.hu/",
    title: "Pioneer",
    tags: ["Production"],
  },
  {
    id: 11,
    url: "http://www.radicalmedia.com/us/directors",
    title: "Radical Media",
    tags: ["Directors"],
  },
  {
    id: 12,
    url: "https://www.kimgehrig.com/work",
    title: "Kim Gehrig",
    tags: ["Director"],
  },
  {
    id: 13,
    url: "https://iconoclast.tv/us/romain-gavras",
    title: "Iconoclast (Romain Gavras)",
    tags: ["Production"],
  },
  {
    id: 14,
    url: "https://allofushere.tv/directors/pleix",
    title: "Pleix",
    tags: ["Collective"],
  },
  { id: 15, url: "https://weareus.co.uk/", title: "Us", tags: ["Creative"] },
  {
    id: 16,
    url: "https://www.canadacanada.com/directors/us",
    title: "Canada (Us)",
    tags: ["Production"],
  },
  {
    id: 17,
    url: "https://www.instagram.com/julienjdm_banana/",
    title: "Julien JDM",
    tags: ["Social"],
  },
  {
    id: 18,
    url: "https://www.youtube.com/@BountyBanana",
    title: "Bounty Banana (YT)",
    tags: ["Video"],
  },
  {
    id: 19,
    url: "https://www.instagram.com/bountybanana/",
    title: "Bounty Banana (IG)",
    tags: ["Social"],
  },
  {
    id: 20,
    url: "https://www.academyfilms.com/garth-davis",
    title: "Academy Films (Garth Davis)",
    tags: ["Film"],
  },
  {
    id: 21,
    url: "https://www.raineallenmiller.com/",
    title: "Raine Allen-Miller",
    tags: ["Director"],
  },
  {
    id: 22,
    url: "https://somesuch.co/directors/raineallen-miller",
    title: "Somesuch",
    tags: ["Production"],
  },
  {
    id: 23,
    url: "http://furlined.com/us/directors/dougal-wilson",
    title: "Furlined (Dougal Wilson)",
    tags: ["Directing"],
  },
  {
    id: 24,
    url: "https://blinkprods.com/talent/dougal-wilson/",
    title: "Blink (Dougal Wilson)",
    tags: ["Production"],
  },
  {
    id: 25,
    url: "https://www.serialpictures.com/directors/brthr/",
    title: "Serial Pictures (BRTHR)",
    tags: ["Visuals"],
  },
  {
    id: 26,
    url: "http://www.smithandfoulkes.co.uk/",
    title: "Smith & Foulkes",
    tags: ["Animation"],
  },
  {
    id: 27,
    url: "https://opositivefilms.com/directors/david-shane",
    title: "O Positive (David Shane)",
    tags: ["Comedy"],
  },
  {
    id: 28,
    url: "https://haroldeinstein.com/",
    title: "Harold Einstein",
    tags: ["Director"],
  },
  {
    id: 29,
    url: "https://vimeo.com/haroldeinstein",
    title: "Harold Einstein (Vimeo)",
    tags: ["Video"],
  },
  {
    id: 30,
    url: "https://www.dantobinsmith.com/",
    title: "Dan Tobin Smith",
    tags: ["Photography"],
  },
  {
    id: 31,
    url: "https://benedictredgrove.com/",
    title: "Benedict Redgrove",
    tags: ["Visual Arts"],
  },
  {
    id: 32,
    url: "http://www.macpremo.com/",
    title: "Mac Premo",
    tags: ["Art"],
  },
  {
    id: 33,
    url: "http://imperial.tv/stacy-wall-s1/",
    title: "Imperial (Stacy Wall)",
    tags: ["Directing"],
  },
  {
    id: 34,
    url: "http://creativity-online.com/credits/stacy-wall/2652/1",
    title: "Stacy Wall (Credits)",
    tags: ["Editorial"],
  },
  {
    id: 35,
    url: "http://www.laurentbarthelemy.com/",
    title: "Laurent Barthelemy",
    tags: ["Design"],
  },
  {
    id: 36,
    url: "https://vimeo.com/warrenfuprojects",
    title: "Warren Fu",
    tags: ["Music Videos"],
  },
  {
    id: 37,
    url: "http://www.josephkosinski.com",
    title: "Joseph Kosinski",
    tags: ["Film"],
  },
  {
    id: 38,
    url: "http://superprimefilms.com/",
    title: "Superprime",
    tags: ["Commercial"],
  },
  {
    id: 39,
    url: "http://imperial.tv/mark-zibert-s1/",
    title: "Imperial (Mark Zibert)",
    tags: ["Production"],
  },
  {
    id: 40,
    url: "https://vimeo.com/d2/",
    title: "Dimension 2 (Vimeo)",
    tags: ["Experimental"],
  },
  {
    id: 41,
    url: "https://dimension2.com/",
    title: "Dimension 2",
    tags: ["Studio"],
  },
  {
    id: 42,
    url: "http://gioacchinopetronicce.com/",
    title: "Gioacchino Petronicce",
    tags: ["Editing"],
  },
  {
    id: 43,
    url: "http://michalmarczak.com/",
    title: "Michal Marczak",
    tags: ["Cinematic"],
  },
  {
    id: 44,
    url: "http://www.pulsefilms.com/director/michal-marczak/commercials",
    title: "Pulse Films",
    tags: ["Global Production"],
  },
  {
    id: 45,
    url: "http://parkpictures.com/chris-wilcha#video-92334969",
    title: "Park Pictures",
    tags: ["Production"],
  },
  {
    id: 46,
    url: "https://www.riffrafffilms.tv/directors/david-wilson",
    title: "Riff Raff (David Wilson)",
    tags: ["Directors"],
  },
  {
    id: 47,
    url: "http://thisisdavidwilson.com/",
    title: "David Wilson",
    tags: ["Creative"],
  },
  {
    id: 48,
    url: "http://prettybird.co/us/talent/creatives/melina-matsoukas/",
    title: "Prettybird (Melina Matsoukas)",
    tags: ["Film"],
  },
  {
    id: 49,
    url: "http://hiromurai.com/",
    title: "Hiro Murai",
    tags: ["Director"],
  },
  {
    id: 50,
    url: "http://www.megaforce.fr/",
    title: "Megaforce",
    tags: ["Collective"],
  },
  {
    id: 51,
    url: "https://www.psyop.com/live-action/",
    title: "Psyop",
    tags: ["Live Action"],
  },
  {
    id: 52,
    url: "http://www.iconoclast.tv/usa/we-are-from-la/",
    title: "Iconoclast (WAFLA)",
    tags: ["Directing"],
  },
  {
    id: 53,
    url: "https://vimeo.com/wearefromla",
    title: "We Are From LA",
    tags: ["Music Videos"],
  },
  {
    id: 54,
    url: "https://www.valentinpetit.fr/",
    title: "Valentin Petit",
    tags: ["Director"],
  },
  {
    id: 55,
    url: "https://www.instagram.com/valentinpetit90",
    title: "Valentin Petit (IG)",
    tags: ["Social"],
  },
  {
    id: 56,
    url: "https://www.gatewoodcreative.com/",
    title: "Gatewood Creative",
    tags: ["Design"],
  },
  {
    id: 57,
    url: "http://www.andrewthomashuang.com/",
    title: "Andrew Thomas Huang",
    tags: ["Visual Art"],
  },
  {
    id: 58,
    url: "https://vimeo.com/user1293099",
    title: "Andrew Thomas Huang (Vimeo)",
    tags: ["Video"],
  },
  {
    id: 59,
    url: "https://www.instagram.com/andrewthomashuang/",
    title: "Andrew Thomas Huang (IG)",
    tags: ["Social"],
  },
  {
    id: 60,
    url: "https://andrewyuyitruong.com/meta-tiger-buffalo",
    title: "Andrew Yuyi Truong",
    tags: ["VFX"],
  },
  {
    id: 61,
    url: "https://biscuitfilmworks.com/us/commercial/steve-rogers/",
    title: "Biscuit (Steve Rogers)",
    tags: ["Commercial"],
  },
  {
    id: 62,
    url: "https://stinkfilms.com/artist/eliot-rausch/",
    title: "Stink Films (Eliot Rausch)",
    tags: ["Production"],
  },
  {
    id: 63,
    url: "https://www.eliotrausch.com/",
    title: "Eliot Rausch",
    tags: ["Director"],
  },
  {
    id: 64,
    url: "http://www.resetcontent.com/ian-pons-jewell",
    title: "Reset (Ian Pons Jewell)",
    tags: ["Directing"],
  },
  {
    id: 65,
    url: "http://furlined.com/us/directors/henry-hobson/",
    title: "Furlined (Henry Hobson)",
    tags: ["Film"],
  },
  {
    id: 66,
    url: "https://vimeo.com/henryhobson",
    title: "Henry Hobson (Vimeo)",
    tags: ["Directing"],
  },
  {
    id: 67,
    url: "http://www.henryhobson.co.uk",
    title: "Henry Hobson",
    tags: ["Creative"],
  },
  {
    id: 68,
    url: "http://www.antibody.tv/index.html",
    title: "Antibody",
    tags: ["Motion"],
  },
  {
    id: 69,
    url: "http://www.ashthorp.com/",
    title: "Ash Thorp",
    tags: ["Visual Development"],
  },
  { id: 70, url: "https://www.altcinc.com/", title: "Alt.vfx", tags: ["VFX"] },
  {
    id: 71,
    url: "http://www.imdb.com/name/nm1085959/",
    title: "Stacy Wall (IMDb)",
    tags: ["Credits"],
  },
  {
    id: 72,
    url: "http://theselby.com/films/",
    title: "The Selby (Films)",
    tags: ["Lifestyle"],
  },
  {
    id: 73,
    url: "http://lernertandsander.com/",
    title: "Lernert & Sander",
    tags: ["Art & Design"],
  },
  {
    id: 74,
    url: "https://www.anonymouscontent.com/work/us/directors/anonymous-content/bardia-zeinali/",
    title: "Anonymous Content (Bardia)",
    tags: ["Production"],
  },
  {
    id: 75,
    url: "https://www.instagram.com/bardiazeinali/",
    title: "Bardia Zeinali",
    tags: ["Director"],
  },
  {
    id: 76,
    url: "http://www.anonymouscontent.com",
    title: "Anonymous Content (Home)",
    tags: ["Production"],
  },
  {
    id: 77,
    url: "http://www.anonymouscontent.com/commercials/anonymous/caryfukunaga/commercials/",
    title: "Anonymous (Cary Fukunaga)",
    tags: ["Commercials"],
  },
  {
    id: 78,
    url: "http://www.gustavjohansson.com",
    title: "Gustav Johansson",
    tags: ["Director"],
  },
  {
    id: 79,
    url: "http://aoifemcardle.com/",
    title: "Aoife McArdle",
    tags: ["Director"],
  },
  {
    id: 80,
    url: "https://www.greatbigstory.com/",
    title: "Great Big Story",
    tags: ["Storytelling"],
  },
  {
    id: 81,
    url: "http://www.biscuitfilmworks.com/noam-murro.html",
    title: "Biscuit (Noam Murro)",
    tags: ["Commercials"],
  },
  {
    id: 82,
    url: "http://www.epochfilms.com/directors/martin-de-thurah/",
    title: "Epoch Films (Martin de Thurah)",
    tags: ["Production"],
  },
  { id: 83, url: "http://dlew.me", title: "David Lew", tags: ["Design"] },
  {
    id: 84,
    url: "http://www.finchcompany.com/",
    title: "Finch",
    tags: ["Production"],
  },
  { id: 85, url: "http://www.b-reel.com/", title: "B-Reel", tags: ["Digital"] },
  {
    id: 86,
    url: "http://www.kinfolk.com/films/",
    title: "Kinfolk (Films)",
    tags: ["Editorial"],
  },
  {
    id: 87,
    url: "https://vimeo.com/mawe",
    title: "Mawe (Vimeo)",
    tags: ["Video"],
  },
  {
    id: 88,
    url: "http://beyondmedals.com",
    title: "Beyond Medals",
    tags: ["Media"],
  },
  {
    id: 89,
    url: "http://boweking.com/",
    title: "Bowe King",
    tags: ["Creative"],
  },
  {
    id: 90,
    url: "http://www.themill.com/portfolio/filter/collection/94/bowe-king",
    title: "The Mill (Bowe King)",
    tags: ["Portfolio"],
  },
  {
    id: 91,
    url: "http://www.lucasallendesigns.com/",
    title: "Lucas Allen",
    tags: ["Design"],
  },
  {
    id: 92,
    url: "http://kapwa.co/robertino-zambrano-director/",
    title: "Kapwa (Robertino Zambrano)",
    tags: ["Animation"],
  },
  {
    id: 93,
    url: "https://www.danperri.com/",
    title: "Dan Perri",
    tags: ["Title Design"],
  },
  {
    id: 94,
    url: "https://www.artofthetitle.com/feature/10-women-of-title-design/",
    title: "Art of the Title (Women)",
    tags: ["Editorial"],
  },
  {
    id: 95,
    url: "https://www.artofthetitle.com/feature/a-fistful-of-titles-the-westerns-of-iginio/",
    title: "Art of the Title (Iginio)",
    tags: ["Editorial"],
  },
  {
    id: 96,
    url: "https://www.gravillisinc.com/",
    title: "Gravillis Inc.",
    tags: ["Branding"],
  },
  {
    id: 97,
    url: "https://the-brandidentity.com/",
    title: "The Brand Identity",
    tags: ["Identity"],
  },
  {
    id: 98,
    url: "https://the-brandidentity.com/searchfilter=tag_application%3ACustom%20Typeface",
    title: "TBI (Custom Type)",
    tags: ["Typeface"],
  },
  {
    id: 99,
    url: "https://the-brandidentity.com/insight/frontify-presents-ragged-edge-and-tilt-discuss-trust-and-tension",
    title: "TBI (Insight)",
    tags: ["Insight"],
  },
  {
    id: 100,
    url: "https://industrialcolor.com/",
    title: "Industrial Color",
    tags: ["Production"],
  },
  {
    id: 101,
    url: "https://blacksmith.tv/",
    title: "Blacksmith",
    tags: ["VFX", "Finish"],
  },
  {
    id: 102,
    url: "https://artandgraft.com/",
    title: "Art&Graft",
    tags: ["Motion", "Brand"],
  },
  {
    id: 103,
    url: "https://futuredeluxe.com/",
    title: "FutureDeluxe",
    tags: ["Experimental"],
  },
  {
    id: 104,
    url: "https://www.extraweg.com/",
    title: "Extraweg",
    tags: ["Digital Art"],
  },
  {
    id: 105,
    url: "https://opticalarts.studio/work/projects/bowers-and-wilkins",
    title: "Optical Arts",
    tags: ["Studio"],
  },
  {
    id: 106,
    url: "https://houseofparliament.com/",
    title: "Parliament",
    tags: ["VFX"],
  },
  {
    id: 107,
    url: "https://www.hellohornet.com/",
    title: "Hornet",
    tags: ["Animation"],
  },
  {
    id: 108,
    url: "https://www.kaspernyman.dk/",
    title: "Kasper Nyman",
    tags: ["Director"],
  },
  {
    id: 109,
    url: "https://glassworksvfx.com/",
    title: "Glassworks",
    tags: ["VFX"],
  },
  {
    id: 110,
    url: "https://dia.tv/",
    title: "DIA",
    tags: ["Branding", "Motion"],
  },
  {
    id: 111,
    url: "https://www.time-based-arts.com/",
    title: "Time Based Arts",
    tags: ["VFX"],
  },
  {
    id: 112,
    url: "https://www.alreadybeenchewed.tv/",
    title: "Already Been Chewed",
    tags: ["Motion"],
  },
  {
    id: 113,
    url: "https://electrictheatre.tv/",
    title: "Electric Theatre",
    tags: ["Collective"],
  },
  { id: 114, url: "https://bgstr.com/", title: "Bigstar", tags: ["Design"] },
  {
    id: 115,
    url: "https://www.weareversus.tv/",
    title: "Versus",
    tags: ["Creative"],
  },
  {
    id: 116,
    url: "https://builders-club.com/",
    title: "Builders Club",
    tags: ["Creative"],
  },
  {
    id: 117,
    url: "https://www.helloscholar.com/",
    title: "Scholar",
    tags: ["Animation"],
  },
  {
    id: 118,
    url: "https://www.psyop.com/",
    title: "Psyop (Global)",
    tags: ["Production"],
  },
  {
    id: 119,
    url: "https://gretelny.com/",
    title: "Gretel",
    tags: ["Branding"],
  },
  {
    id: 120,
    url: "https://www.never-always.com/",
    title: "Never Always",
    tags: ["Studio"],
  },
  {
    id: 121,
    url: "https://shinestudio.com/",
    title: "Shine",
    tags: ["Titles"],
  },
  {
    id: 122,
    url: "https://trollback.com/",
    title: "Trollback",
    tags: ["Design"],
  },
  { id: 123, url: "https://www.yuco.com/", title: "Yu+Co", tags: ["Titles"] },
  {
    id: 124,
    url: "https://playlist.studio/",
    title: "Playlist",
    tags: ["Creative"],
  },
  { id: 125, url: "http://elastic.tv/", title: "Elastic", tags: ["Design"] },
  {
    id: 126,
    url: "https://vimeo.com/104447378",
    title: "Elastic (Vimeo)",
    tags: ["Video"],
  },
  {
    id: 127,
    url: "https://brandnewschool.com/work",
    title: "Brand New School",
    tags: ["Creative"],
  },
  {
    id: 128,
    url: "https://www.chapeaustudios.com/apple-chapeau",
    title: "Chapeau",
    tags: ["Design"],
  },
  {
    id: 129,
    url: "https://www.instagram.com/brutworks/",
    title: "Brut",
    tags: ["Animation"],
  },
  {
    id: 130,
    url: "https://flutterfilms.tv/",
    title: "Flutter",
    tags: ["Production"],
  },
  {
    id: 131,
    url: "http://kuntzel-deygas.com/",
    title: "Kuntzel+Deygas",
    tags: ["Studio"],
  },
  {
    id: 132,
    url: "http://1stavemachine.com",
    title: "1stAveMachine",
    tags: ["Production"],
  },
  {
    id: 133,
    url: "https://www.mainframe.co.uk/",
    title: "Mainframe",
    tags: ["VFX"],
  },
  {
    id: 134,
    url: "http://serialcut.com/",
    title: "Serial Cut",
    tags: ["Image"],
  },
  {
    id: 135,
    url: "http://www.brothersmcleod.co.uk/",
    title: "Brothers McLeod",
    tags: ["Animation"],
  },
  {
    id: 136,
    url: "http://www.blind.com/work/type/featured/",
    title: "Blind",
    tags: ["Design"],
  },
  {
    id: 137,
    url: "http://linetest.tv",
    title: "Linetest",
    tags: ["Production"],
  },
  {
    id: 138,
    url: "http://www.josephychan.com",
    title: "Joseph Chan",
    tags: ["Creative"],
  },
  {
    id: 139,
    url: "http://www.artonemotion.com",
    title: "Art on Emotion",
    tags: ["Motion"],
  },
  {
    id: 140,
    url: "http://mk12.com/MKXII/",
    title: "MK12",
    tags: ["Collective"],
  },
  {
    id: 141,
    url: "http://www.laundrymat.tv/work",
    title: "Laundry",
    tags: ["Design"],
  },
  {
    id: 142,
    url: "http://www.peterqu.in",
    title: "Peter Quinn",
    tags: ["Motion"],
  },
  {
    id: 143,
    url: "https://vimeo.com/albinholmqvist/videos",
    title: "Albin Holmqvist",
    tags: ["Visuals"],
  },
  {
    id: 144,
    url: "http://www.meandthebootmaker.com",
    title: "The Bootmaker",
    tags: ["Creative"],
  },
  {
    id: 145,
    url: "http://www.tbik-design.com/work",
    title: "TBIK",
    tags: ["Design"],
  },
  {
    id: 146,
    url: "http://www.alasdairwillson.com",
    title: "Alasdair Willson",
    tags: ["Visuals"],
  },
  {
    id: 147,
    url: "http://www.michaelrigley.com/",
    title: "Michael Rigley",
    tags: ["Design"],
  },
  {
    id: 148,
    url: "http://hueandcry.tv",
    title: "Hue & Cry",
    tags: ["Animation"],
  },
  {
    id: 149,
    url: "https://www.behance.net/mexicangry",
    title: "Mexicangry",
    tags: ["Creative"],
  },
  {
    id: 150,
    url: "http://adsoftheworld.com/creative/jorge_calleja",
    title: "Jorge Calleja",
    tags: ["Director"],
  },
  {
    id: 151,
    url: "http://www.mrkaplin.com/",
    title: "Mr. Kaplin",
    tags: ["Design"],
  },
  {
    id: 152,
    url: "http://www.shanegriffin.nyc/",
    title: "Shane Griffin",
    tags: ["Director"],
  },
  {
    id: 153,
    url: "http://www.sundayafternoon.us/",
    title: "Sunday Afternoon",
    tags: ["Creative"],
  },
  {
    id: 154,
    url: "http://www.emanuelecolombo.it",
    title: "Emanuele Colombo",
    tags: ["Motion"],
  },
  { id: 155, url: "http://chips.nyc/", title: "Chips", tags: ["Creative"] },
  {
    id: 156,
    url: "https://www.hyejungbae.com/",
    title: "Hyejung Bae",
    tags: ["Design"],
  },
  { id: 157, url: "http://fynng.com/", title: "Fynn Ng", tags: ["Creative"] },
  {
    id: 158,
    url: "https://panoply.co.uk/",
    title: "Panoply",
    tags: ["Design"],
  },
  {
    id: 159,
    url: "http://encyclopediapictura.com",
    title: "Encyclopedia Pictura",
    tags: ["Film"],
  },
  { id: 160, url: "https://www.cheatit.co/", title: "Cheat", tags: ["Color"] },
  {
    id: 161,
    url: "https://www.luxartists.net/artists",
    title: "Lux Artists",
    tags: ["Talent"],
  },
  {
    id: 162,
    url: "http://www.lassefrank.com/categories/show_commercials_3",
    title: "Lasse Frank",
    tags: ["Cinematography"],
  },
  {
    id: 163,
    url: "http://www.edugrau.com/commercials",
    title: "Edu Grau",
    tags: ["Commercials"],
  },
  { id: 164, url: "http://jdefdp.com/", title: "J.D.F", tags: ["Creative"] },
  {
    id: 165,
    url: "http://niklasjohansson.com",
    title: "Niklas Johansson",
    tags: ["Cinematography"],
  },
  {
    id: 166,
    url: "http://adamnewportberra.com",
    title: "Adam Newport-Berra",
    tags: ["Director"],
  },
  {
    id: 167,
    url: "http://www.christianweber.net",
    title: "Christian Weber",
    tags: ["Photography"],
  },
  {
    id: 168,
    url: "https://rinayang.com/",
    title: "Rina Yang",
    tags: ["Cinematography"],
  },
  {
    id: 169,
    url: "https://www.adolphoveloso.com/",
    title: "Adolpho Veloso",
    tags: ["Director"],
  },
  {
    id: 170,
    url: "https://www.mkoenigswieser.com/",
    title: "M. Koenigswieser",
    tags: ["Director"],
  },
  {
    id: 171,
    url: "http://rockpaperscissors.com/",
    title: "Rock Paper Scissors",
    tags: ["Edit"],
  },
  {
    id: 172,
    url: "https://www.cartel.tv/editors/leo-scott",
    title: "Cartel (Leo Scott)",
    tags: ["Editorial"],
  },
  { id: 173, url: "http://company3.com/", title: "Company 3", tags: ["Color"] },
  { id: 174, url: "http://www.a52.com/", title: "A52", tags: ["VFX"] },
  {
    id: 175,
    url: "http://www.framestore.com/",
    title: "Framestore",
    tags: ["VFX", "Animation"],
  },
  {
    id: 176,
    url: "http://www.natashanewmanthomas.com/",
    title: "Natasha Newman-Thomas",
    tags: ["Styling"],
  },
  { id: 177, url: "http://heyhush.com/work/", title: "Hush", tags: ["Design"] },
  {
    id: 178,
    url: "http://silasveta.com/work",
    title: "Sila Sveta",
    tags: ["Media"],
  },
  {
    id: 179,
    url: "http://www.barbecue-design.de",
    title: "Barbecue",
    tags: ["Design"],
  },
  {
    id: 180,
    url: "http://jonpasang.com/",
    title: "Jon Pasang",
    tags: ["Creative"],
  },
  {
    id: 181,
    url: "http://www.w0w.co.jp/en/works/",
    title: "WOW",
    tags: ["Visual Design"],
  },
  {
    id: 182,
    url: "http://gmunk.com/BOX-DEMO",
    title: "GMUNK (BOX)",
    tags: ["Creative"],
  },
  {
    id: 183,
    url: "http://www.ryojiikeda.com/",
    title: "Ryoji Ikeda",
    tags: ["Sound/Visual"],
  },
  {
    id: 184,
    url: "https://www.nowness.com/story/son-lux-breathe-out-adrian-moyse-junta",
    title: "Son Lux (Adrian Moyse)",
    tags: ["Director"],
  },
  {
    id: 185,
    url: "http://www.triplewidemedia.com/2015/02/2015-super-bowl-halftime-show/",
    title: "TripleWide",
    tags: ["Projection"],
  },
  {
    id: 186,
    url: "http://www.raketamedia.com/Sochi-2014-Video-Projections",
    title: "Raketamedia",
    tags: ["Visuals"],
  },
];
